export { default as mult_text } from "./MultText.vue";
export { default as single_choice } from "./SingleChoice.vue";
export { default as mult_choice } from "./MultChoice.vue";
export { default as score } from "./Score.vue";
export { default as fill_blanks } from "./FillBlanks.vue";
export { default as nps } from "./NPS.vue";
export { default as pagination } from "./Pagination.vue";
export { default as sort } from "./Sort.vue";
export { default as matrix_radio } from "./MatrixRadio.vue";
export { default as matrix_blanks } from "./MatrixBlanks.vue";
export { default as matrix_check } from "./MatrixCheck.vue";
export { default as matrix_scores } from "./MatrixScores.vue";
export { default as increase_table } from "./IncreaseTable.vue";
export { default as select } from "./Select.vue";
export { default as cascader } from "./Cascader.vue";
export { default as upload } from "./Upload.vue";
export { default as time } from "./DateTimePicker.vue";
export { default as score_text } from "./ScoreText.vue";
export { default as signature } from "./Signature.vue";

// export { default as paragraph } from "./Paragraph.vue";
