export enum typeEnum {
  single_choice = "单选题",
  mult_choice = "多选题",
  mult_text = "文本题",
  sort = "排序题",
  matrix_radio = "矩阵单选",
  matrix_check = "矩阵多选",
  matrix_blanks = "矩阵填空",
  matrix_scores = "矩阵打分",
  fill_blanks = "多项填空",
  increase_table = "自增表格",
  nps = "NPS量表",
  score = "打分题",
  select = "下拉题",
  cascader = "级联题",
  time = "时间选择",
  upload = "文件上传",
  signature = "签名",
  score_text = "评分题",
}
